#==========================================================
#= SPRING CLOUD API GATEWAY
#==========================================================
spring:
  cloud:
    gateway:
      enabled: true
      httpclient:
        connect-timeout: 50000
        response-timeout: 50s
      routes:
        - id: studentService
          uri: lb://STUDENT
          predicates:
            - Path=/api/v1/student/**
            - Path=/student/**
        - id: studentCardService
          uri: lb://STUDENT-CARD
          predicates:
            - Path=/api/v1/student_card/**
            - Path=/student_card/**

#==========================================================
#= SERVER
#==========================================================
server:
  port: 8765

#==========================================================
#= LOGGING
#==========================================================
logging:
  file.name: './logs/api-gateway.log'
  level:
    org.springframework.cloud: debug
  logback:
    rolling policy:
      max-file-size: 100MB

#==========================================================
#= EURELA CLIENT
#==========================================================
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10

#==============================================================
#= SPRING ACTUATOR
#==============================================================
management:
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics

#==============================================================
#= SPRING ACTUATOR INFO
#==============================================================
info:
  application:
    name: ${spring.application.name}
    version: ${spring.application.version}
    spring-version: ${spring.version}
  support:
    author: "TheAppleGeeK"
    mail: "weibin.xu.dev@gmail.com"