spring:
  cloud:
    gateway:
      enabled: true
      httpclient:
        connect-timeout: 50000
        response-timeout: 50s
      routes:
        - id: studentService
          uri: lb://STUDENT
          predicates:
            - Path=/api/v1/student/**
        - id: studentCardService
          uri: lb://STUDENT-CARD
          predicates:
            - Path=/api/v1/student_card/**

server:
  port: 8765

logging:
  file.name: './logs/api-gateway.log'
  level:
    org.springframework.cloud: debug
  logback:
    rolling policy:
      max-file-size: 100MB

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10