#==========================================================
#= LOGGING
#==========================================================
logging:
  file.name: './logs/config-server.log'
  level:
    org.springframework.cloud: info
  logback:
    rolling policy:
      max-file-size: 100MB

#==============================================================
#= SPRING ACTUATOR
#==============================================================
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh

#==============================================================
#= SPRING ACTUATOR INFO
#==============================================================
info:
  application:
    name: ${spring.application.name}
    version: ${spring.application.version}
    spring-version: ${spring.version}
  support:
    author: "TheAppleGeeK"
    mail: "weibin.xu.dev@gmail.com"