spring:
  #==========================================================
  #= SPRING CLOUD BUS
  #==========================================================
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
  #==========================================================
  #= APACHE KAFKA
  #==========================================================
  kafka:
    bootstrap-servers:
      - ${KAFKA_ADDR:http://kafka:29092}
    client-id: ${spring.application.name}:${spring.profiles.active}:8080(seq)
  #==========================================================
  #= SPRING CLOUD ZIPKIN
  #==========================================================
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web
    message-timeout: 5
  #==========================================================
  #= SPRING CLOUD SLEUTH
  #==========================================================
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: false

#==========================================================
#= SERVER
#==========================================================
server:
  port: 8761

#==========================================================
#= EUREKA SERVER
#==========================================================
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

#==============================================================
#= SPRING ACTUATOR
#==============================================================
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,bus-refresh,bus-env

#==============================================================
#= SPRING ACTUATOR INFO
#==============================================================
info:
  application:
    name: ${spring.application.name}
    version: ${spring.application.version}
    spring-version: ${spring.version}
  support:
    author: "TheAppleGeeK"
    mail: "weibin.xu.dev@gmail.com"