spring:
  #==========================================================
  #= DATABASE CONNECTION
  #==========================================================
  datasource:
    url: jdbc:postgresql://student-db/student
    username: postgres
    password: Password01!
  #==========================================================
  #= SPRING DATA JPA
  #==========================================================
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  #==========================================================
  #= SPRING CLOUD BUS
  #==========================================================
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
  #==========================================================
  #= APACHE KAFKA
  #==========================================================
  kafka:
    bootstrap-servers:
      - ${KAFKA_ADDR}:${spring.kafka.url}
    client-id: ${spring.application.name}:8080(seq)
    url: http://kafka:9092

#==========================================================
#= SERVER
#==========================================================
server:
  port: 8080
  error:
    include-message: always

#==========================================================
#= LOGGING
#==========================================================
logging:
  file.name: './logs/Student.log'
  level:
    web: info
    org.hibernate: info
    it.theapplegeek.clients: debug
  logback:
    rolling policy:
      max-file-size: 100MB

#==========================================================
#= EUREKA CLIENT
#==========================================================
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10

#==============================================================
#= SPRING ACTUATOR
#==============================================================
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /student/actuator
      exposure:
        include: health,info,metrics,refresh,bus-refresh

#==============================================================
#= SPRING ACTUATOR INFO
#==============================================================
info:
  application:
    name: ${spring.application.name}
    version: ${spring.application.version}
    spring-version: ${spring.version}
  support:
    author: "TheAppleGeeK"
    mail: "weibin.xu.dev@gmail.com"